# Generated by Django 4.1.5 on 2023-08-04 17:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('author', models.CharField(default='anonym', max_length=100)),
                ('publishDate', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
