# Generated by Django 4.1.5 on 2023-08-01 00:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_alter_article_date_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='date_created',
        ),
        migrations.AddField(
            model_name='article',
            name='publishDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
