# Generated by Django 4.1.5 on 2023-07-29 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('price', models.FloatField(null=True)),
                ('description', models.CharField(max_length=200, null=True)),
                ('image', models.ImageField(blank=True, default='testProduct.png', null=True, upload_to='')),
                ('stock', models.IntegerField(null=True)),
            ],
        ),
    ]
