# Generated by Django 4.1.5 on 2023-08-02 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0004_alter_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart',
            fields=[
                ('cartId', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('firstname', models.CharField(default='defualt_firstname', max_length=200)),
                ('lastname', models.CharField(default='defualt_lastname', max_length=200)),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('CUSTOMER', 'Customer')], default='ADMIN', max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='users.user')),
                ('CustomerId', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
            bases=('users.user',),
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('cart_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('cartId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.cart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='inCart',
            field=models.ManyToManyField(blank=True, to='users.cartitem'),
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('GoalId', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('Finished', models.BooleanField(default=False)),
                ('comment', models.CharField(default='no comment', max_length=200)),
                ('dueDate', models.DateField()),
                ('CustomerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.customer')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='goals',
            field=models.ManyToManyField(blank=True, to='users.goal'),
        ),
        migrations.AddField(
            model_name='cart',
            name='CustomerId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.customer'),
        ),
    ]
