# Generated by Django 4.1.5 on 2023-07-30 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='users.user')),
                ('CustomerId', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
            bases=('users.user',),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('CUSTOMER', 'Customer')], default='ADMIN', max_length=50),
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('GoalId', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('Finished', models.BooleanField(default=False)),
                ('comment', models.CharField(default='no comment', max_length=200)),
                ('dueDate', models.DateField()),
                ('CustomerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.customer')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='goals',
            field=models.ManyToManyField(blank=True, to='users.goal'),
        ),
    ]
