# Generated by Django 4.1.5 on 2023-07-30 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customer_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='username',
        ),
    ]
